### ISSUE TITLE
Tracking issue: Add Array API standard support

### ISSUE THREAD

**Issue by mtsokol** [finch-tensor/finch-jl-python#21]
Hi @willow-ahrens @hameerabbasi,
This issue is meant to track progress of implementing Array API standard for `finch-tensor`.
I thought that we could try adding short notes to bullet-points, saying which `Finch.jl` functions should be called to implement given entry. I think we already had some ideas during one of our first calls.
Array API: https://data-apis.org/array-api/latest/index.html

A note to those who edit this list in the future: Convert bullets to issues, not subissues, as you complete them. Otherwise they get removed from the list.
### main namespace
- [x] `astype` - https://github.com/willow-ahrens/finch-tensor/pull/15 - eager
- [x] element-wise ops (`add`, `multiply`, `cos`, ...) - https://github.com/willow-ahrens/finch-tensor/pull/17 (partially...)
- [x] reductions (`xp.prod`, `xp.sum`) - `jl.sum` and `jl.prod`, also just `jl.reduce` - https://github.com/willow-ahrens/finch-tensor/pull/17
- [x] `matmul` - implemented with `finch.tensordot` for non-stacked input. Should be rewritten with `jl.mul` / Finch einsum.
- [x] `tensordot` - `finch.tensordot` - https://github.com/willow-ahrens/finch-tensor/pull/22
- [x] `where` - `jl.broadcast(jl.ifelse, cond, a, b)` - https://github.com/willow-ahrens/finch-tensor/pull/30
- [x] #90
- [ ] `take` - `jl.getindex` eager for now
- [x] `nonzero` - this is an eager function, but it is implemented as `ffindnz(arr)` - https://github.com/willow-ahrens/finch-tensor/pull/30
- [x] creation functions: `asarray`, `ones`, `full`, `full_like`, ... - `finch.Tensor` constructor, as well as `jl.copyto!(arr, jl.broadcasted(Scalar(1))`, as well as changing the default of the tensor with `Tensor(Dense(Element(1.0)))`. We may need to distinguish some of these. https://github.com/willow-ahrens/finch-tensor/pull/28, https://github.com/willow-ahrens/finch-tensor/pull/32
- [x] #106
- [ ] set functions: `unique_all`, `unique_counts`, `unique_inverse`, `unique_values` - eager
- [x] `all`, `any`
- [ ] `concat` - eager for now
- [x] #109
- [ ] `flip` -eager for now
- [x] #107
- [ ] `roll` - eager for now
- [x] #108
- [ ] `stack` - eager for now
- [ ] `argsort`/`sort` - eager
- [ ] `broadcast_arrays` - eager for now
- [ ] `broadcast_to` - eager for now
- [x] `can_cast`/`finfo`/`iinfo`/`result_type`
- [x] bitwise ops: `bitwise_and`/`bitwise_left_shift`/`bitwise_invert`/`bitwise_or`/`bitwise_right_shift`/`bitwise_xor`
- [ ] Boolean indexing (https://data-apis.org/array-api/latest/API_specification/indexing.html#boolean-array-indexing)
### `linalg` namespace
(I copied those from the [benchmark suite](https://github.com/Quansight-Labs/array-api-benchmarks/blob/main/benchmarks/linalg.py). If something turns out to be unfeasible we can drop it.)
- [ ] `linalg.vecdot` - `finch.tensordot`
-[+] [x] `linalg.vector_norm` - `finch.norm` - https://github.com/finch-tensor/finch-tensor-python/pull/94[/+][-] [ ] `linalg.vector_norm` - `finch.norm`[/-]
- [ ] `linalg.trace` - eager
- [ ] `linalg.tensordot` - implemented in the main namespace. Just needs an alias
- [x] #89
- [ ] `linalg.cross` - eager for now
- [ ] `linalg.matrix_transpose` - lazy
- [ ] `linalg.matrix_power` - eager (call matmul on sparse matrix until it gets too dense)
- [ ] `linalg.matrix_norm` - for `nuc` or `2`, call external library. For `fro`, `inf`, `1`, `0`, `-1`, `-inf`, call `jl.norm`.
- [x] #110
- [ ] `xp.linalg.cholesky` - call CHOLMOD or something
- [ ] `xp.linalg.det` - call EIGEN or something
- [ ] `xp.linalg.eigh` - call external library
- [ ] `xp.linalg.eigvalsh` - call external library
- [x] `xp.linalg.inv` - call external library - `scipy.sparse.linalg.inv`
- [ ] `xp.linalg.matrix_rank` - call external library
- [ ] `xp.linalg.pinv` - call external library
### `Tensor` methods and attributes
- [ ] `Tensor.to_device()` - `finch.moveto`
### miscellaneous
- [ ] handling scalars
- [ ] benchmarking
- [ ] Don't forget about [__array_namespace_info__()](https://data-apis.org/array-api/latest/API_specification/inspection.html) function, and the isdtype() and result_type() [data type functions](https://data-apis.org/array-api/latest/API_specification/data_type_functions.html) 🙂

**Comment by willow-ahrens** [comment]
I added some methods you can call for most of these! Some of them need to be external library calls

**Comment by mtsokol** [comment]
@willow-ahrens thank you - that's exactly what I needed! 😄

**Comment by jorenham** [comment]
Don't forget about [`__array_namespace_info__()`](https://data-apis.org/array-api/latest/API_specification/inspection.html) function, and the `isdtype()` and `result_type()` [data type functions](https://data-apis.org/array-api/latest/API_specification/data_type_functions.html) 🙂

**Comment by willow-ahrens** [comment]
Thanks! Added a bullet for it.

**Comment by ilan-gold** [comment]
Hello!

Re: https://github.com/finch-tensor/finch-tensor-python/pull/88 I think the root of this is having a way to do boolean indexing for us.

I don't see anything here about boolean indexing (https://data-apis.org/array-api/latest/API_specification/indexing.html#boolean-array-indexing) along axes. And from what I can tell, it's not supported in the julia library (or it is but only as a custom loop: https://github.com/finch-tensor/Finch.jl/blob/2e89d2228a777a8238eccd145cfa6a7b405eb76c/docs/src/docs/language/mask_sugar.md?plain=1#L5); however it is part of the array-api.

Is there a plan to support it?  I would really love to use this but lacking a proper indexing method is a big blocker (assuming I have this right).

**Comment by willow-ahrens** [comment]
@ilan-gold Hi Ilan! Thanks for your interest in the project! Our goal is to support all of the operations in the array API, so if something has been left out it likely wasn't intentional. It is quite feasible to implement this operation, and I've added it to the list! The only caveat is that I don't think we will be able to implement it in a way that can fuse it with other operations, at least for now. I think I left it out of the julia implementation just because I needed to get things up and running quickly, but Boolean indexing is actually part of the Julia indexing api as well, so this addition is in scope for both languages!

**Comment by ilan-gold** [comment]
> that can fuse it with other operations

Could you highlight what this would mean practically for users? This is mostly a performance, not a practical (in the sense of "all downstream operations will break if you boolean index" thing), no?

**Comment by willow-ahrens** [comment]
Yes, this is a performance thing, not a semantics thing. What it would mean for users is just that if we wish to do a logical indexing operation, we would need to materialize the inputs and outputs of the operation (This is normal for most libraries, Finch just provides a special fusion optimization for certain operations).

**Comment by ilan-gold** [comment]
Right, ok, interesting.  Thanks @willow-ahrens I'll keep my ear to the ground in the meantime.  Your library is a big target for us using the array-api, really looking forward to digging into it a bit more!

**Comment by mtsokol** [comment]
> `linalg.matrix_norm` - for `nuc` or `2`, call external library. For `fro`, `inf`, `1`, `0`, `-1`, `-inf`, call `jl.norm`.

@willow-ahrens Isn't the Frobenius (`fro`) norm equivalent to `2`? If so, is it supported by `jl.norm` here?

**Comment by mtsokol** [comment]
>  linalg.matrix_norm - for nuc or 2, call external library. For fro, inf, 1, 0, -1, -inf, call jl.norm.

@willow-ahrens I think that for matrix norms [jl.opnorm](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.opnorm) should be used instead of `jl.norm` as `jl.norm` is for vector norms, right? If so, I think that `jl.opnorm` doesn't support Finch tensors.

**Comment by lucascolley** [comment]
> [@ilan-gold](https://github.com/ilan-gold) Hi Ilan! Thanks for your interest in the project! Our goal is to support all of the operations in the array API, so if something has been left out it likely wasn't intentional. It is quite feasible to implement this operation, and I've added it to the list! The only caveat is that I don't think we will be able to implement it in a way that can fuse it with other operations, at least for now. I think I left it out of the julia implementation just because I needed to get things up and running quickly, but Boolean indexing is actually part of the Julia indexing api as well, so this addition is in scope for both languages!

hi @willow-ahrens ! Any news on boolean indexing? Here is an example of `sparse` getting stuck:

```console
>>> x = sparse.asarray(np.arange(3))
>>> mask = np.asarray([True, False, True])
>>> x
SwizzleArray(Tensor(Dense{Int64}(Element{0, Int64, Int64}([0, 1, 2]), 3)), (1,))
>>> x[mask]
Traceback (most recent call last):
  File "<python-input-16>", line 1, in <module>
    x[mask]
    ~^^^^^^
  File "/Users/lucascolley/ghq/github.com/pydata/sparse/.pixi/envs/finch/lib/python3.13/site-packages/finch/tensor.py", line 274, in __getitem__
    key = _add_plus_one(key, self.shape)
  File "/Users/lucascolley/ghq/github.com/pydata/sparse/.pixi/envs/finch/lib/python3.13/site-packages/finch/tensor.py", line 1366, in _add_plus_one
    idx = normalize_axis_tuple(idx, size)
  File "/Users/lucascolley/ghq/github.com/pydata/sparse/.pixi/envs/finch/lib/python3.13/site-packages/numpy/_core/numeric.py", line 1469, in normalize_axis_tuple
    axis = tuple(normalize_axis_index(ax, ndim, argname) for ax in axis)
  File "/Users/lucascolley/ghq/github.com/pydata/sparse/.pixi/envs/finch/lib/python3.13/site-packages/numpy/_core/numeric.py", line 1469, in <genexpr>
    axis = tuple(normalize_axis_index(ax, ndim, argname) for ax in axis)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.bool' object cannot be interpreted as an integer
>>> x[sparse.asarray(mask)]
Traceback (most recent call last):
  File "<python-input-17>", line 1, in <module>
    x[sparse.asarray(mask)]
    ~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/pydata/sparse/.pixi/envs/finch/lib/python3.13/site-packages/finch/tensor.py", line 276, in __getitem__
    result = self._obj[key]
             ~~~~~~~~~^^^^^
  File "/Users/lucascolley/.julia/packages/PythonCall/83z4q/src/JlWrap/any.jl", line 269, in __getitem__
    return self._jl_callmethod($(pyjl_methodnum(pyjlany_getitem)), k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
juliacall.JuliaError: ArgumentError: invalid index: <py SwizzleArray(Tensor(Dense{Int64}(Element{false, Bool, Int64}(Bool[1, 0, 1]), 3)), (1,))> of type Py
Stacktrace:
 [1] to_index(i::Py)
   @ Base ./indices.jl:315
 [2] to_index(A::Finch.SwizzleArray{(1,), Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, PyArray{Int64, 1, true, true, Int64}}}}}, i::Py)
   @ Base ./indices.jl:292
 [3] to_indices
   @ ./indices.jl:368 [inlined]
 [4] getindex(arr::Finch.SwizzleArray{(1,), Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, PyArray{Int64, 1, true, true, Int64}}}}}, inds::Py)
   @ Finch ~/.julia/packages/Finch/ucnKV/src/interface/index.jl:63
 [5] pyjlany_getitem(self::Finch.SwizzleArray{(1,), Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, PyArray{Int64, 1, true, true, Int64}}}}}, k_::Py)
   @ PythonCall.JlWrap ~/.julia/packages/PythonCall/83z4q/src/JlWrap/any.jl:81
 [6] _pyjl_callmethod(f::Any, self_::Ptr{PythonCall.C.PyObject}, args_::Ptr{PythonCall.C.PyObject}, nargs::Int64)
   @ PythonCall.JlWrap ~/.julia/packages/PythonCall/83z4q/src/JlWrap/base.jl:65
 [7] _pyjl_callmethod(o::Ptr{PythonCall.C.PyObject}, args::Ptr{PythonCall.C.PyObject})
   @ PythonCall.JlWrap.Cjl ~/.julia/packages/PythonCall/83z4q/src/JlWrap/C.jl:63
```

**Comment by lucascolley** [comment]
I guess this still needs implementation at the Julia level?

```console
julia> A = [1, 2, 3]
3-element Vector{Int64}:
 1
 2
 3

julia> mask = A .> 1
3-element BitVector:
 0
 1
 1

julia> A[mask]
2-element Vector{Int64}:
 2
 3

julia> B = Tensor([1, 2, 3])
3 Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, Vector{Int64}}}}:
 1
 2
 3

julia> mask = B .> 1
3 Tensor{DenseLevel{Int64, ElementLevel{false, Bool, Int64, Vector{Bool}}}}:
 0
 1
 1

julia> B[mask]
ERROR: MethodError: no method matching keys(::IndexLinear, ::Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, Vector{Int64}}}})
The function `keys` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  keys(::IndexStyle, ::AbstractArray, AbstractArray...)
   @ Base abstractarray.jl:404
  keys(::DataStructures.MultiDict, ::Any...)
   @ DataStructures ~/.julia/packages/DataStructures/qUuAY/src/delegate.jl:21
  keys(::DataStructures.Trie{K, V}, ::Any) where {K, V}
   @ DataStructures ~/.julia/packages/DataStructures/qUuAY/src/trie.jl:78
  ...

Stacktrace:
 [1] eachindex(::IndexLinear, ::Tensor{DenseLevel{Int64, ElementLevel{0, Int64, Int64, Vector{Int64}}}})
   @ Base ./abstractarray.jl:318
 [2] to_indices
   @ ./indices.jl:360 [inlined]
 [3] getindex(arr::Tensor{DenseLevel{Int64, ElementLevel{…}}}, inds::Tensor{DenseLevel{Int64, ElementLevel{…}}})
   @ Finch ~/.julia/packages/Finch/ucnKV/src/interface/index.jl:52
 [4] top-level scope
   @ REPL[38]:1
```

EDIT: for completeness:

```console
>>> x = finchlite.asarray([1, 2, 3])
>>> x > 1
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/interface/eager.py", line 216, in __gt__
    return greater(self, other)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/interface/eager.py", line 1015, in greater
    return compute(lazy.greater(x1, x2))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/interface/fuse.py", line 167, in compute
    res = ctx(prgm)
          ^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/autoschedule/normalize.py", line 77, in __call__
    return self.ctx(root, bindings)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/autoschedule/executor.py", line 80, in __call__
    res = mod.main(*args)
          ^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 244, in __call__
    return self.ctx(ntn.Call(self.func, args_i))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 368, in __call__
    return f_e(*args_e)
           ^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 500, in my_func
    ctx_2(body)
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 446, in __call__
    self(body)
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 446, in __call__
    self(body)
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 446, in __call__
    self(body)
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 458, in __call__
    self.slots[tns.name] = declare(tns_e, init_e, op_e, shape_e)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/finch_notation/interpreter.py", line 188, in declare
    return tns.declare(init, op, shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/compile/bufferized_ndarray.py", line 84, in declare
    self.val.store(i, init)
  File "/Users/lucascolley/ghq/github.com/finch-tensor/finch-tensor-lite/src/finchlite/codegen/numpy_buffer.py", line 72, in store
    self.arr[index] = value
    ~~~~~~~~^^^^^^^
ValueError: setting an array element with a sequence.
```
